server:
  port: 8090

spring:
  datasource:
    #url: jdbc:mysql:///ssm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    url: jdbc:mysql://139.196.86.99:3306/competition?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: 131428
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root


  redis:
    host: 139.196.86.99
    port: 6379
    password: 131428
    lettuce:
      pool:
        max-idle: 3000000
        max-wait: 3000000
        max-active: 3000000
    timeout: 3000000
  servlet:
    multipart:
      max-file-size: 1GB
      max- request-size: 1GB


mybatis:
  mapper-locations: classpath:xml/*.xml   #mapper配置文件的位置
  type-aliases-package: com.taotie.wechatpro.dao #entity存放对应的实体对象